//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T3H_Cap04.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notas
    {
        public int Id { get; set; }
        public string Idaluno { get; set; }
        public string Nota { get; set; }
        public int AlunosMFCod { get; set; }
    
        public virtual AlunosMF AlunosMF { get; set; }
    }
}
